### ISSUE TITLE
Power Page slider error

### ISSUE THREAD

**Issue by Feichtmeier** [Feichtmeier/settings#114]
```bash
Restarted application in 375ms.

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building LayoutBuilder:
'package:flutter/src/material/slider.dart': Failed assertion: line 147 pos 15: 'value >= min && value <= max': is not true.

The relevant error-causing widget was
LayoutBuilder LayoutBuilder:file:///home/frederik/Projects/settings/lib/view/widgets/slider_settings_row.dart:71:22
When the exception was thrown, this was the stack
#2      new Slider
#3      SliderSettingsRow.build.<anonymous closure>
#4      _LayoutBuilderElement._layout.layoutCallback
#5      BuildOwner.buildScope
#6      _LayoutBuilderElement._layout
#7      RenderObject.invokeLayoutCallback.<anonymous closure>
#8      PipelineOwner._enableMutationsToDirtySubtrees
#9      RenderObject.invokeLayoutCallback
#10     RenderConstrainedLayoutBuilder.rebuildIfNecessary
#11     _RenderLayoutBuilder.performLayout
#12     RenderObject.layout
#13     ChildLayoutHelper.layoutChild
#14     RenderFlex._computeSizes
#15     RenderFlex.performLayout
#16     RenderObject.layout
#17     ChildLayoutHelper.layoutChild
#18     RenderFlex._computeSizes
#19     RenderFlex.performLayout
#20     RenderObject.layout
#21     RenderPadding.performLayout
#22     RenderObject.layout
#23     RenderConstrainedBox.performLayout
#24     RenderObject.layout
#25     ChildLayoutHelper.layoutChild
#26     RenderFlex._computeSizes
#27     RenderFlex.performLayout
#28     RenderObject.layout
#29     ChildLayoutHelper.layoutChild
#30     RenderFlex._computeSizes
#31     RenderFlex.performLayout
#32     RenderObject.layout
#33     RenderPadding.performLayout
#34     RenderObject.layout
#35     RenderProxyBoxMixin.performLayout
#36     RenderObject.layout
#37     RenderPadding.performLayout
#38     RenderObject.layout
#39     ChildLayoutHelper.layoutChild
#40     RenderFlex._computeSizes
#41     RenderFlex.performLayout
#42     RenderObject.layout
#43     RenderConstrainedBox.performLayout
#44     RenderObject.layout
#45     RenderPadding.performLayout
#46     RenderObject.layout
#47     RenderPositionedBox.performLayout
#48     RenderObject.layout
#49     _RenderSingleChildViewport.performLayout
#50     RenderObject.layout
#51     RenderProxyBoxMixin.performLayout
#52     RenderObject.layout
#53     RenderProxyBoxMixin.performLayout
#54     RenderObject.layout
#55     RenderProxyBoxMixin.performLayout
#56     RenderObject.layout
#57     RenderProxyBoxMixin.performLayout
#58     RenderObject.layout
#59     RenderProxyBoxMixin.performLayout
#60     RenderObject.layout
#61     RenderProxyBoxMixin.performLayout
#62     RenderObject.layout
#63     RenderProxyBoxMixin.performLayout
#64     RenderObject.layout
#65     RenderProxyBoxMixin.performLayout
#66     RenderCustomPaint.performLayout
#67     RenderObject.layout
#68     RenderProxyBoxMixin.performLayout
#69     RenderObject.layout
#70     RenderProxyBoxMixin.performLayout
#71     RenderObject.layout
#72     RenderProxyBoxMixin.performLayout
#73     RenderObject.layout
#74     RenderProxyBoxMixin.performLayout
#75     RenderObject.layout
#76     MultiChildLayoutDelegate.layoutChild
#77     _ScaffoldLayout.performLayout
#78     MultiChildLayoutDelegate._callPerformLayout
#79     RenderCustomMultiChildLayoutBox.performLayout
#80     RenderObject._layoutWithoutResize
#81     PipelineOwner.flushLayout
#82     RendererBinding.drawFrame
#83     WidgetsBinding.drawFrame
#84     RendererBinding._handlePersistentFrameCallback
#85     SchedulerBinding._invokeFrameCallback
#86     SchedulerBinding.handleDrawFrame
#87     SchedulerBinding._handleDrawFrame
#91     _invoke (dart:ui/hooks.dart:150:10)
#92     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#93     _drawFrame (dart:ui/hooks.dart:114:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════
```

Only happens when I close the notebook, video attaching ...

https://user-images.githubusercontent.com/15329494/135720659-d2a84f31-3e83-40f5-a3f4-55bbd3d06854.mp4

**Comment by Feichtmeier** [comment]
'package:flutter/src/material/slider.dart': Failed assertion: line 147 pos 15: 'value >= min && value <= max': is not true.

when the screen of the notebook is disabled this error pops up
when you set the min value of the slidersettingsrow to -1 it works again

![Peek 2021-10-02 16-32](https://user-images.githubusercontent.com/15329494/135721060-1842ed91-c223-42f5-8052-063e1e33bf84.gif)

**Comment by Feichtmeier** [comment]
still happens
