### ISSUE TITLE
Failed to load dynamic library 'libgio-2.0.so'

### ISSUE THREAD

**Issue by asimfarooq5** [Feichtmeier/settings#174]
Using Ubuntu 21.10, the app fails to start
```
asim@linux-machine:~/flutter/settings$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on Ubuntu 21.10 5.13.0-21-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by asimaarbi** [comment]
Here is the startup logs
```
asim@linux-machine:~/flutter/settings$ flutter run -d linux
Launching lib/main.dart on Linux in debug mode...
/snap/flutter/current/usr/bin/ld: warning: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/crt1.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002
Building Linux application...                                           
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libgio-2.0.so': libgio-2.0.so: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
#2      gio (package:gsettings/src/gio.dart:9:45)
#3      new GSettings._new (package:gsettings/src/settings.dart:266:22)
#4      new GSettings (package:gsettings/src/settings.dart:252:40)
#5      main (package:settings/main.dart:20:25)
#6      main (file:///home/asim/flutter/settings/.dart_tool/flutter_build/generated_main.dart:53:42)
#7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:143:38)
#8      _rootRun (dart:async/zone.dart:1428:13)
#9      _CustomZone.run (dart:async/zone.dart:1328:19)
#10     _runZoned (dart:async/zone.dart:1863:10)
#11     runZonedGuarded (dart:async/zone.dart:1851:12)
#12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:141:5)
#13     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

Syncing files to device Linux...                                   146ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:36127/SHW-k1fdw5U=/
Lost connection to device.
```

**Comment by Feichtmeier** [comment]
Hi there 😊

Did you install flutter with the snap?

**Comment by asimaarbi** [comment]
Yes, that's true. That's the official way of installing flutter on Ubuntu

**Comment by Feichtmeier** [comment]
> Yes, that's true. That's the official way of installing flutter on Ubuntu

Ok :) currently there is a little problem with the flutter snap and 21.10 but this will be fixed soon.
If you don't want to wait.
Remove the snap
Then

```
sudo apt install git curl cmake meson make clang libgtk-3-dev pkg-config
mkdir ~/developed
cd ~/developed
git clone https://github.com/flutter/flutter.git -b master
echo 'export PATH="$PATH:$HOME/developed/flutter/bin"' >> ~/.bashrc
flutter config --enable-linux-desktop
```

**Comment by asimfarooq5** [comment]
Thanks, I have tried the suggested way and It's working now.

**Comment by Feichtmeier** [comment]
Great, thanks for pinging back :)
