### ISSUE TITLE
Bluetooth page crash without bluetooth dongle

### ISSUE THREAD

**Issue by Jupi007** [Feichtmeier/settings#204]
This only happens when I don't have my bluetooth dongle connected.

If you click on the bluetooth page, and then on any another one, the app throw an exception when dispose the `firstAdapter` service:

```
════════ Exception caught by widgets library ══════════
The following LateError was thrown while finalizing the widget tree:
LateInitializationError: Field 'firstAdapter' has not been initialized.

When the exception was thrown, this was the stack
#0      BluetoothModel.firstAdapter (package:settings/view/pages/bluetooth/bluetooth_model.dart)
#1      BluetoothModel.dispose
#2      ChangeNotifierProvider._dispose
#3      _CreateInheritedProviderState.dispose
#4      _InheritedProviderScopeElement.unmount
#5      _InactiveElements._unmount
#6      _InactiveElements._unmount.<anonymous closure>
#7      ComponentElement.visitChildren
#8      _InactiveElements._unmount
#9      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#10     _InactiveElements._unmountAll
#11     BuildOwner.lockState
#12     BuildOwner.finalizeTree
#13     WidgetsBinding.drawFrame
#14     RendererBinding._handlePersistentFrameCallback
#15     SchedulerBinding._invokeFrameCallback
#16     SchedulerBinding.handleDrawFrame
#17     SchedulerBinding._handleDrawFrame
#21     _invoke (dart:ui/hooks.dart:151:10)
#22     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#23     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
═══════════════════════════════════
```

**Comment by Feichtmeier** [comment]
It's a duplicate of #194 :D

**Comment by Jupi007** [comment]
Sorry 🤕 😥
